# This is a basic workflow to help you get started with Actions

name: Merge from Dev to Main (Release)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version of Release (semver)"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge-dev-to-main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          
      - name: Merge dev to main
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git checkout -b release/${{ github.event.inputs.releaseVersion }}
          git push origin release/${{ github.event.inputs.releaseVersion }}
          git checkout main
          git pull
          git merge --no-ff release/${{ github.event.inputs.releaseVersion }} -m "Auto-merge dev to main"
          git push
